version: "3.8"
services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: weazzy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      custom_net:
        ipv4_address: 10.5.0.5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      custom_net:
        ipv4_address: 10.5.0.6
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres


volumes:
  postgres: {}
  pgadmin: {}


networks:
  custom_net:
    driver: bridge  # тип связи между контейнерами
    ipam:
      config:
        - subnet: 10.5.0.0/16  # подсеть в формате CIDR , представляющая сегмент сети
          gateway: 10.5.0.1